In [2]:
%pip install numpy matplotlib scikit-learn einops

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 28.7 MB/s  0:00:006.5 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 30.0 MB/s  0:00:00 41.2 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 29.7 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 34.5 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 36.9 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 40.1 MB/s  0:00:002.0 MB/s eta 0:00:0101
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [matplotlib]7m━━━ 11/12 [matplotlib]
Note: you may need to restart the kernel to use updated packages.


# Numpy and Matplotlib

Hello everyone, today we will see how to use Numpy and Matplotlib in order to make some graph and some matrix calculation.

# Table of content

1. [Numpy](#Numpy)
2. [Matplotlib](#Matplotlib)

#  Numpy

Numpy is a library that allows us to make some matrix calculation and some graph. It's a very powerful library that is used in a lot of other library like Tensorflow, Pytorch, Scikit-learn, etc... For today, we will see how to use it in order to make some matrix calculation and some graph. It's one of the lib that is the most used in the world of data science and machine learning. Knowing how to use that lib is the first step to become a data scientist or a machine learning engineer :). So let's start by a bit of theory and then we will see how to use it.

## What is a matrix?

Matrix are table of elements, like numbers or characters. It's a very useful tool in mathematics and in computer science. It's used in a lot of domain like machine learning, data science, etc... It's a very powerful tool that allows us to make some calculation that we can't do with a simple number. It allowed us to make calculations in different dimension and can create link between them. So let's see how look a matrix like :
![Matrix](assets/Matrix.png)

Here m and n are numbers who are numbers belonging of N (all number between 0 and infinity). The matrix is composed by m rows and n columns. Here each elements of the matrix are represented by a square. Now, we will learn how to create, manipulate and use matrix...

In [44]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

plt.style.use('seaborn-v0_8-whitegrid')
import einops

## Matrix calculation

Let's start by making some matrix calculation. First, we will see how to create a matrix and then we will see how to make some calculation with it.

In [ ]:
# let's make a matrix filled by zeros in 2 dimention by using Numpy

def create_two_dimention_matrix_zeros(size_dim1 : int, size_dim2 : int):
    matrix_zero = np.zeros((size_dim1, size_dim2))
    return matrix_zero

matrix_zeros = create_two_dimention_matrix_zeros(12, 90)
assert (matrix_zeros.shape[0] == 12 and matrix_zeros.size == 1080 and matrix_zeros.max() == 0 and matrix_zeros.min() == 0), "Not yet try again"
print("Well done!")

Well done!


In [54]:
# let's create another one but this time filled by random value between 1 and 0

def create_two_dimention_matrix_randoms(size_dim1 : int, size_dim2 : int):
    matrix_random = np.random.random((size_dim1, size_dim2))
    print(matrix_random)
    return matrix_random

matrix_random = create_two_dimention_matrix_randoms(5, 6)
assert (matrix_random.shape[0] == 5 and matrix_random.size == 30 and matrix_random.max() <= 1.0 and matrix_random.min() >= 0.0), "no no no, try again"
print("Continue like that!")

[[0.70050968 0.51385642 0.03653737 0.41968553 0.35379508 0.3248717 ]
 [0.77434169 0.66930686 0.23431828 0.59042232 0.4095684  0.16681848]
 [0.19162746 0.99029569 0.27243508 0.69556161 0.92362865 0.33553819]
 [0.7867011  0.13407229 0.28242052 0.09270408 0.53802409 0.47660924]
 [0.36877496 0.60278242 0.75869471 0.63120595 0.88967125 0.10222397]]
Continue like that!


In [ ]:
# let's now make some calcul with numpy, what do I mean with that it's that we have to add 1 at number of the random matrix 

def add_1(matrix):
    
    pass

## Multiplication of matrix

Now that we know how to create a matrix and how to make some calculation with it, let's see how to multiply 2 matrix. Be careful, it's not the same as multiplying 2 number... Goog luck! :)

In [ ]:
# let's now add multiply 2 matrix together
# I will let you also make the assertion that the matrix are able to be multiply together

def multiply_matrix(matrix1, matrix2):
    pass

assert (multiply_matrix(matrix_random, matrix_zeros) == "The matrix are not able to be multiply together" and multiply_matrix(np.array([[1, 2]]), np.array([[2], [1]])) == np.array([4])), "No no no, try again"

## Averages calculation

Now that we know how to multiply 2 matrix together, let's see how to calculate the average of each element of a matrix.

In [ ]:
# Calculate the average of each element of a matrix

def calculate_average(matrix):
    pass

matrix = np.array([[1, 2, 3], [3, 3, 3], [7, 10, 13]])

assert (calculate_average(np.array(matrix)) == 5.0), "No no no, try again"


In [ ]:
# Calculate the standart deviation of each element of a matrix

def calculate_standart_deviation(matrix):
    pass

assert (calculate_standart_deviation(np.array(matrix)) == 3.858612300930075), "No no no, try again"


In [ ]:
# Calculate the variance of each element of a matrix

def calculate_variance(matrix):
    pass

assert (calculate_variance(np.array(matrix)) == 14.88888888888889), "No no no, try again"


## Matplotlib

### Graph

Now that we know how to make some matrix calculation, let's see how to make some graph with matplotlib. We will see how to make some simple graph in 2D and then we will see how to make some more complex graph in 3D.

### show intersection between 2 function

Let's start by something simple, we want to see the intersection between 2 function.

So first, we will create 2 function, and then we will see how to show the intersection between them. the first function will be :

 $$ \begin{equation*}
    f(x) = sinh(x) / tan(x)
   \end{equation*} $$

In [ ]:
def f(x):
    pass

assert (f(1) == 0.7545880086758965 and f(2) == -1.6598600642614152), "No no no, try again"

The second function will be a $$ \begin{equation*}
    g(x) = cosh(x) / \sqrt {e^x}
   \end{equation*} $$

In [ ]:
def g(x):
    pass

assert (g(1) == 0.93592571542427898 and g(2) == 1.3840344484134546), "No no no, try again"

In [ ]:
# Let's make a function that shows the intersection between 2 function

def show_intersection(function1, function2, start, end):
    x = np.linspace(start, end, 100)
    ...
    plt.show()

show_intersection(f, g, -1, 1)

## BONUS - 3D Graph
Before that we create our first AI, let's discover how to make a 3D schem

In [ ]:
# Now let's try to make a cap in mathematics, so let's make a function that make 1/4 of a circle.

def one_fourth_of_a_circle(r: float):
    pass

In [ ]:
def show_2d(r: float = 1.0):
    _, ax = plt.subplots(1)
    
    ...
        
    plt.xlim(0 ,1.25)
    plt.ylim(0 ,1.25)

show_2d()

That was easy!!!
Now, let's try to put that line in a 3D space.
(You can use again, your function one_fourth_of_a_circle) 

In [ ]:
def create_arc_surface_3d(r: float = 1.0):
    pass

create_arc_surface_3d()

Now that you have the basis, now let's create our cap!!!

A little tips, now, you have to adapt your first code to make it in 3d.

In [ ]:
def creat_a_cap_3d(r: float = 1.0):
    ...
    x, y, z = ...
    
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    
    ax.plot_surface(x, y, z, color='b', alpha=0.6)
    ax.set_aspect('auto')
    
    plt.xlim(-1.25, 1.25)
    plt.ylim(-1.25, 1.25)
    
    plt.show()

creat_a_cap_3d()